version: 2.1

orbs:
  vst: vst/vst-native-orb@3.0.0

.current_filters: &current_filters
  branches:
    only:
      - main
      - /^pr-ci\/.+/

.params: &params
  package-name: "vstvideoutils"
  vcs-fingerprint: "50:cd:dd:0b:2a:e7:af:b8:24:b2:00:6d:75:5e:57:1a"

commands:
  setup-libavformat:
    description: >
      Installs libavformat on linux
    steps:
      - run:
          name: Install libavformat
          command: apt -y install libavformat-dev

  update-git-submodules:
    description: >
      Update git submodules
    steps:
      - run:
          command: git submodule update --init

  extra-gitlab-tokens:
    description: >
      Additional gitlab tokens
    steps:
      - run:
          command: conan user gitlab+deploy-token-473993 -r vst-libs -p $GITLAB_API_KEY2

jobs:
  build:
    description: >
      Build for Emscripten

    executor: vst/linux

    parameters:
      package-name:
        type: string
        default: ""
      vcs-fingerprint:
        type: string
        default: ""

    steps:
      - vst/setup:
          vcs-fingerprint: << parameters.vcs-fingerprint >>
      - update-git-submodules
      - vst/setup-linux
      - vst/setup-linux-cmake
      - setup-libavformat
      - vst/install-conan-and-configure
      - extra-gitlab-tokens
      - vst/build:
          profile: "emscripten"
          type: "Release"
      - vst/build:
          profile: "emscripten"
          type: "Debug"
      - vst/upload:
          package-name: << parameters.package-name >>


workflows:
  version: 2
  build:
    jobs:
      - build:
          <<: *params
          filters:
            <<: *current_filters
