version: 2.1

orbs:
  vst: vst/vst-native-orb@5.0.3

.current_filters: &current_filters
  branches:
    only:
      - main
      - /^pr-ci\/.+/

.params: &params
  package-name: "vstvideoutils"
  vcs-fingerprint: "50:cd:dd:0b:2a:e7:af:b8:24:b2:00:6d:75:5e:57:1a"

commands:
  setup-libavformat:
    description: >
      Installs libavformat on linux
    steps:
      - run:
          name: Install libavformat
          command: apt -y install libavformat-dev

  build:
    description: >
      Build conan package.

    parameters:
      profile:
        type: string
        default: "none"
      type:
        type: string
        default: "Release"
      build-timeout:
        type: string
        default: "10m"

    steps:
      - run:
          name: Build << parameters.profile >>  << parameters.type >>
          when: always
          no_output_timeout: << parameters.build-timeout >>
          command: |
            deps=${CIRCLE_BRANCH##*@}
            if [ "$deps" = "${CIRCLE_BRANCH}" ]; then
              deps=""
              channel=${CIRCLE_BRANCH//[_+=.,\/]/-}
            else
              channel=${CIRCLE_BRANCH%@*}
              channel=${channel//[_+=.,\/]/-}
            fi

            tmpdir="tmp/<< parameters.profile >>/<< parameters.type >>"
            mkdir -p $tmpdir
            echo "Building for << parameters.profile >> on ${channel} for << parameters.type >>; pr_deps '${deps}'"
            conan install conan -pr << parameters.profile >> -s "build_type=<< parameters.type >>" -o "pr_deps=${deps}" -if $tmpdir
            conan build conan -bf $tmpdir -sf .
            conan export-pkg -bf $tmpdir conan "vernierst+vst-libs/${channel}" -pr << parameters.profile >> -s "build_type=<< parameters.type >>" -o "pr_deps=${deps}" -sf .

            if [ "Release" = "<< parameters.type >>" ]; then
              echo "Package release package"
              conan export-pkg -bf $tmpdir conan "vernierst+vst-native-modules-release/${channel}" -pr << parameters.profile >> -s "build_type=<< parameters.type >>" -o "pr_deps=${deps}" -sf .
            fi

  upload-release:
    description: >
      Upload release packages.
    parameters:
      package-name:
        type: string
        default: ""

    steps:
      - run:
          name: Upload vst-native-modules-release
          when: always
          command: |
            channel=${CIRCLE_BRANCH//[_+=.,\/]/-}
            echo "Uploading to " ${channel}
            conan user gitlab+deploy-token-296862 -p $GITLAB_API_KEY -r gitlab
            conan upload -c -r gitlab --force --all "<< parameters.package-name >>/*@vernierst+vst-native-modules-release/${channel}"


jobs:
  build:
    description: >
      Build for Emscripten

    executor: vst/linux

    parameters:
      package-name:
        type: string
        default: ""
      vcs-fingerprint:
        type: string
        default: ""

    steps:
      - vst/setup:
          vcs-fingerprint: << parameters.vcs-fingerprint >>
      - vst/setup-linux
      - vst/setup-linux-cmake
      - vst/install-conan-and-configure
      - build:
          profile: "emscripten"
          type: "Release"
      - build:
          profile: "emscripten"
          type: "Debug"
      - vst/upload:
          package-name: << parameters.package-name >>
      - upload-release:
          package-name: << parameters.package-name >>


workflows:
  version: 2
  build:
    jobs:
      - build:
          <<: *params
          filters:
            <<: *current_filters
