version: 2

defaults: &defaults
  working_directory: ~/repo
  machine: 
    image: ubuntu-1604:201903-01

jobs:
  build:
    <<: *defaults 
    steps:
      - checkout
      - run:
          name: Run Build
          command: bash ./ci/build.sh
      - persist_to_workspace:
          root: ~/repo
          paths: 
            - .
  deploypatch:
    <<: *defaults  
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publishing patch
          command: sh ./ci/publish.sh patch
  deployminor:
    macos:
      xcode: "10.2.1"
    steps:
      - run:
          name: Publishing minor
          command: bash ./ci/publish.sh minor
  deploymajor:
    macos:
      xcode: "10.2.1"
    steps:
      - run:
          name: Publishing major
          command: sh ./ci/publish.sh major

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - deploypatch:
          requires:
            - build
          filters:
            tags:
              only: /^patch/
            branches:
              ignore: /.*/
      - deployminor:
          requires:
            - build
          filters:
            tags:
              only: /^minor/
            branches:
              ignore: /.*/
      - deploymajor:
          requires:
            - build
          filters:
            tags:
              only: /^major/
            branches:
              ignore: /.*/
