version: 2

defaults: &defaults
  working_directory: ~/repo
  machine: 
    image: ubuntu-1604:201903-01


jobs:
  build:
    <<: *defaults 
    steps:
      - checkout
      - run: # print the name of the branch we're on
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Run Build
          command: bash ./ci/build.sh
      - run: # print the name of the branch we're on
          name: "What branch am I on2?"
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: set var
          command: mkdir -p workspace
      - run: echo "export BRANCH=${CIRCLE_BRANCH}" >> workspace/new-env-vars
      - run: cat workspace/new-env-vars >> $BASH_ENV
      - run: 
          name: Testing branch
          command: echo "$BRANCH"
      - run: 
          name: Testing new-env-vars
          command: cat workspace/new-env-vars
      - persist_to_workspace:
          root: ~/repo
          paths: 
            - .
  deploypatch:
    <<: *defaults  
    steps:
      - attach_workspace:
          at: ~/repo
      - checkout
      - run:
          name: Publishing patch
          command: sh ./ci/publish.sh patch
      - run: cat workspace/new-env-vars >> $BASH_ENV
      - run: echo "$BRANCH"
  deployminor:
    <<: *defaults  
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Publishing minor
          command: bash ./ci/publish.sh minor
  deploymajor:
    <<: *defaults  
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Publishing major
          command: sh ./ci/publish.sh major

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      - deploypatch:
          requires:
            - build
          filters:
            tags:
              only: /^patch/
            branches:
              ignore: /.*/
      - deployminor:
          requires:
            - build
          filters:
            tags:
              only: /^minor/
            branches:
              ignore: /.*/
      - deploymajor:
          requires:
            - build
          filters:
            tags:
              only: /^major/
            branches:
              ignore: /.*/
