version: 2

defaults: &defaults
  working_directory: ~/repo
  machine: 
    image: ubuntu-1604:201903-01


jobs:
  vst-video-utils:
    <<: *defaults 
    steps:
      - checkout
      - run: 
          name: Init submodules
          command: sh ./ci/ciScripts/initSubmodules.sh
      - run:
          name: Install Dependencies
          command: sh ./ci/ciScripts/installDependencies.sh
      - run:
          name: Install CMake
          command: |
            wget https://github.com/Kitware/CMake/releases/download/v3.18.0/cmake-3.18.0-Linux-x86_64.tar.gz
            tar -xvf cmake-3.18.0-Linux-x86_64.tar.gz 
            export PATH=/home/circleci/repo/cmake-3.18.0-Linux-x86_64/bin:$PATH
            cmake --version
      - run:
          name: Build
          command: |
            sh ./ci/ciScripts/activateEmsdk.sh
            cd emsdk
            . ./emsdk_env.sh
            ./emsdk list
            emcc -v
            echo $EMSDK
            cd ..
            export PATH=/home/circleci/repo/cmake-3.18.0-Linux-x86_64/bin:/opt/circleci/.pyenv/versions/2.7.12/bin/:$PATH
            pyenv global 2.7.12
            python --version
            bash ./build.sh     
      - store_artifacts:
          path: ./build/dist
          destination: dist
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$minorgal_NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Check version and deploy
          command: bash ./ci/ciScripts/checkVersions.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - vst-video-utils:
          filters:
            branches:
              only: master
