version: 2

defaults: &defaults
  working_directory: ~/repo
  machine: 
    image: ubuntu-1604:201903-01


jobs:
  build:
    <<: *defaults 
    steps:
      - checkout
      - run:
          name: Run Build
          command: bash ./ci/build.sh
      - persist_to_workspace:
          root: ~/repo
          paths: 
            - .

  deploy:
    <<: *defaults  
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Check version and deploy
          command: bash ./ci/ciScripts/checkVersions.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
