version: 2

defaults: &defaults
  working_directory: ~/repo
  machine: 
    image: ubuntu-1604:201903-01


jobs:
  build-for-deploy:
    <<: *defaults 
    steps:
      - checkout
      - run:
          name: Run Build
          command: bash ./ci/build.sh
      - persist_to_workspace:
          root: ~/repo
          paths: 
            - .
  build:
    <<: *defaults 
    steps:
      - checkout
      - run:
          name: Run Build
          command: bash ./ci/build.sh
      - persist_to_workspace:
          root: ~/repo
          paths: 
            - .

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/ 
